name: 'Saplings - Editorial'
description: 'Configures a rich editing experience for modern Drupal.'
type: 'Site'
recipes:
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  - saplings-full-html-editor
install:
  # Core.
  - contextual
  - node
  - views
  # Contrib.
  - access_unpublished
  - environment_indicator
  - quick_node_clone
  - sam
  - tour
  - trash
  - view_unpublished
  - views_bulk_edit
config:
  strict: false
  import:
    node:
      - views.view.content
    views_bulk_edit: '*'
  actions:
    # Add some permissions to the Content editor role.
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
      grantPermissions:
        - 'access content overview'
        - 'access contextual links'
        - 'view any unpublished content'
