name: 'Saplings - Editorial'
description: 'Configures a rich editing experience for modern Drupal.'
type: 'Site'
install:
  # Core.
  - ckeditor5
  - editor
  - media
  - node
  - tour
  # Contrib.
  - access_unpublished
  - editor_advanced_link
  - linkit
  - nomarkup
  - quick_node_clone
  - responsive_tables_filter
  - view_unpublished
config:
  import:
    access_unpublished: '*'
    linkit: '*'
    quick_node_clone: '*'
    responsive_tables_filter: '*'
